# generated by discussions/correlation from "schepens" repository;
# provides matrix c1 which contains all correlations of the 54 locations, and
# matrix locations with the respective location indices
load("spatial_correlations.RData")	

colpal = colorRampPalette(c('white', 'blue', 'black'))
cv = colpal(265)

plotCorr <- function(from, to, ...)
{
	fromx = locations[from, 1]
	fromy = locations[from, 2]
	tox = locations[to, 1]
	toy = locations[to, 2]
	#lines(c(fromx, tox), c(fromy, toy), ...)
	arrows(fromx, fromy, tox, toy, angle=15, length=0.1, code=3, ...)
}

#largest100 = head(sort(c1, decreasing=T), 1000)
sorted = sort(c1, decreasing=T)
largestNpercent = function(n)
	sorted[sorted>=quantile(c1, na.rm=T, probs=(100-n)/100)]

plotLargestNpercent <- function(n, show.colorbar=TRUE)
{
	coeffs = largestNpercent(n)
	plot(
		locations, 
		xaxt="n", yaxt="n", 
		xlab="", ylab="", 
		xlim=c(1, 9 + ifelse(show.colorbar, 0.5, 0)),
		bty = "n",
		main=sprintf("Largest %i%%\t(N=%i)", n, length(coeffs)))
	lapply(
		rev(coeffs), 
		function(x) {
			mx = which(c1==x, arr.ind=T); 
			plotCorr(mx[1], mx[2], col=cv[round(256*x)], lwd=2*abs(x))})
	if(show.colorbar)
	{
		for(k in 1:256)
		{
			ybottom = 7*(k-1)/256 + 1
			ytop = ybottom+7/256
			rect(9.5, ybottom, 10, ytop, col=cv[k], border=NA)
		}
		axis(4, at=seq(1, 8, length=5), labels=seq(0, 1, length=5))
	}
}

pdf("correlations%d.pdf", onefile=F, height=6.5, width=7.25)
op = par(mar=c(0, 0, 4, 2)+0.1)
plotLargestNpercent(2)
plotLargestNpercent(5)
plotLargestNpercent(10)
plotLargestNpercent(50)
par(op)
dev.off()
